# Generated by Django 2.2.10 on 2020-05-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myprof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='article_image',
            field=models.ImageField(default='', editable=False, upload_to='main/'),
        ),
    ]
