# Generated by Django 2.2.10 on 2020-06-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myprof', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='article_image',
        ),
    ]
