# Generated by Django 2.2.10 on 2020-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myprof', '0002_project_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='article_image',
            field=models.ImageField(upload_to='main/'),
        ),
    ]
